#!/bin/bash
#SBATCH --job=apply_masks
#SBATCH --output=logs/apply_masks%j.out
#SBATCH --error=logs/apply_masks%j.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=4G
#SBATCH --time=01:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=eh0560@princeton.edu

module purge
module load anaconda3/2023.3
conda activate torch_env

python /scratch/gpfs/eh0560/RotationNet/src/RotationNet/apply_segmentation_masks.py
