#!/bin/bash

#SBATCH --job=train_model
#SBATCH --output=logs/train_model%j.out
#SBATCH --error=logs/train_model%j.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=64G
#SBATCH --gres=gpu:1
#SBATCH --constraint=gpu80
#SBATCH --time=00:05:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=eh0560@princeton.edu

module purge
module load anaconda3/2023.9
conda activate ffcv

export OMP_NUM_THREADS=2
export WANDB_MODE=offline

uid=$(date +%s)

torchrun \
--nnodes 1 \
--nproc_per_node 1 \
/scratch/gpfs/eh0560/RotationNet/src/RotationNet/model/train_ffcv.py \
$uid \
/scratch/gpfs/eh0560/RotationNet/model_training_configs/DryRun.json
